---
- hosts: all
  become: yes
  tasks:
    - name: Install Docker, psql, and Docker Compose dependencies (apt)
      apt:
        name:
          - docker.io
          - postgresql-client
          - python3-pip 
        state: present
        update_cache: true
    
    - name: Install Docker Compose, Ansible 'docker' module dependencies (pip)
      pip:
        name:
          - docker
          - docker-compose
        state: present

